name: deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Hetzner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - run: npm i
      - run: npm run build
      - run: rsync -avz -e "ssh -l www" dist/ cherf.ais-ucla.org:/www/www.ais-ucla.org

